### ISSUE TITLE
ClassNotFoundException: Didn't find class "sqip.internal.event.LogEventsResponse"

### ISSUE THREAD

**Issue by xesun** [square/in-app-payments-flutter-plugin#80] opened 2019-12-07 06:48 UTC
### Expected behavior

**Environment (please complete the following information):**

**Comment by okenshields** [comment] 2019-12-17 22:18
We released a new version (1.3.1) for Android today https://developer.squareupstaging.com/docs/changelog/mobile-logs/2019-12-17 which should help fix this issue. Please let us know if you still experience any issues. Thanks!

**Comment by StephenJosey** [comment] 2020-01-16 23:46
Closing as duplicate of https://github.com/square/in-app-payments-flutter-plugin/issues/72

**Closed by StephenJosey** 2020-01-16 23:46 UTC
Labels: bug, duplicate
