### ISSUE TITLE
packages out of date, conflicts

### ISSUE THREAD

**Issue by sgehrman** [square/in-app-payments-flutter-plugin#94] opened 2020-03-08 07:50 UTC
Because no versions of build_runner match >1.8.0 <2.0.0 and build_runner 1.8.0 depends on build_daemon ^2.1.0, build_runner ^1.8.0 requires build_daemon ^2.1.0.
And because build_daemon <2.1.1 depends on stream_transform ^0.0.14+1 and build_daemon >=2.1.1 depends on built_value ^7.0.0, build_runner ^1.8.0 requires stream_transform ^0.0.14+1 or built_value ^7.0.0.
And because therapist_training depends on square_in_app_payments ^1.3.0 which depends on built_value ^6.1.5, build_runner ^1.8.0 requires stream_transform ^0.0.14+1.

So, because therapist_training depends on both stream_transform ^1.2.0 and build_runner ^1.8.0, version solving failed.
pub get failed (1; So, because therapist_training depends on both stream_transform ^1.2.0 and build_runner ^1.8.0, version solving failed.)
exit code 1

**Comment by StephenJosey** [comment] 2020-03-24 15:40
Thanks for reporting. We're looking into updating the packages and will keep you posted.

**Comment by mayankgenie** [comment] 2020-04-07 11:23
any updates on this? Do you have an ETA?

**Comment by StephenJosey** [comment] 2020-06-02 17:13
Closing as duplicate of: https://github.com/square/in-app-payments-flutter-plugin/issues/87

**Closed by StephenJosey** 2020-06-02 17:13 UTC
Labels: bug, duplicate
