### ISSUE TITLE
Lost connection to device on back button tap

### ISSUE THREAD

**Issue by PizzaLober** [square/in-app-payments-flutter-plugin#82] opened 2019-12-18 01:16 UTC
I having a problem with the plugin when tapping the back button on a  new flutter project with Android X support. The app launches the card entry form but when tapping the back button it loses connection and the app ends.  

[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.535], 
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.5)
[√] VS Code, 64-bit edition (version 1.41.0)
[√] Connected device (1 available)

Also how can I modify error messages that say 'Something went wrong. Please contact the developer of this application and provide them with this error code:'?

Thanks

**Comment by okenshields** [comment] 2019-12-18 21:21
@PizzaLober , thanks for reporting the issue.
I suspect the problem you were hitting was a known issue fixed in a new release (1.3.1) of the underlying In-app payment SDK for Android: https://developer.squareupstaging.com/docs/changelog/mobile-logs/2019-12-17
Can you follow instructions in https://github.com/square/in-app-payments-flutter-plugin/blob/master/doc/versioning.md to update to latest version and see it fixes your issue
That particular error message that you were seeing is not customizable at this point. Thanks!

**Comment by PizzaLober** [comment] 2019-12-19 16:20
@okenshields Thank you for your answer.

I have updated to  sqipVersion = '1.3.1'  but unfortunately got the same result. 
Could it be related to pos Flutter v1.12 since it introduced changes on how plugins  are registered. 
(https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects#add-to-app-migration)

Are you able to reproduce the bug?
1) creating a new Flutter project (Channel stable, v1.12.13+hotfix.5)
2) importing plugin v1.3.0 (sqipVersion = '1.3.0' or sqipVersion = '1.3.1')  
3) copying .dart files from plugin example
4) launch credit card entry and tap back button

Thanks.

**Comment by okenshields** [comment] 2019-12-21 00:54
@PizzaLober , I was able to reproduce this issue with Flutter v1.12.13+hotfix.5. And it does look like the issue is related to Flutter 1.12 breaking API changes. Will you be able to use older version of Flutter to create your app?
We will need to investigate further and decide what can be done to support both new and old versions of Flutter.

**Comment by PizzaLober** [comment] 2019-12-23 15:31
Thanks. I look forward for updates.

**Comment by sgehrman** [comment] 2020-01-18 09:21
same issue, doesn't work at all.  I try to make a payment using the example code and it just quits the app.  Any progress on this?

**Comment by Wahidsmn** [comment] 2020-02-04 02:18
Hi any update on this issue? I am having the same problem.

**Comment by PizzaLober** [comment] 2020-02-07 14:39
Hi everyone,

Any update on this?

**Comment by sgehrman** [comment] 2020-02-14 03:47
Been waiting over a month now.  Any updates?

**Comment by utpalruparel** [comment] 2020-02-18 11:37
We are facing same issue. Is there any solution without downgrade?

**Comment by StephenJosey** [comment] 2020-02-26 17:35
Hey folks, unfortunately no update on this yet. We're still looking into it and will let you know once we have an update.

**Comment by sgehrman** [comment] 2020-05-02 01:13
Is this project dead?  Zero updates for months now and it doesn't work.

**Comment by StephenJosey** [comment] 2020-06-02 16:39
Hi, this project is certainly not dead, and we apologize for the delay here. We're definitely still working on resolving this issue and will update it as soon as we can.

**Comment by jspkm** [comment] 2020-06-16 05:52
Hi - Any update on status resolving this issue?

**Comment by mohsin-sq** [comment] 2020-06-24 20:59
Hi, 

We made a change to support Flutter 1.12+ and are working on verifying if this issue is fixed.

**Comment by mohsin-sq** [comment] 2020-07-10 17:53
The changes have been pushed to the package manager. Please upgrade to the latest version of the plugin and see if that has fixed your issue! Let me know if you have any concerns!

**Comment by mohsin-sq** [comment] 2020-07-15 17:13
I'll be closing this issue as the issue should be resolved. Please feel free to re-open if something changes!

**Closed by mohsin-sq** 2020-07-15 17:13 UTC
Labels: bug
