### ISSUE TITLE
Lost Connection to device after saving card details

### ISSUE THREAD

**Issue by aifrosals** [square/in-app-payments-flutter-plugin#85] opened 2020-01-16 10:27 UTC
I am using the code in the example section and when I enter the card details and tap on save, the program terminates
  
  Here is the log:
  ```
 I/flutter (10898): curl --request POST https://connect.squareupsandbox.com/v2/locations/SQUARE_LOCATION_ID/transactions \--header "Content-Type: application/json" \--header "Authorization: Bearer YOUR_ACCESS_TOKEN" \--header "Accept: application/json" \--data '{"idempotency_key": "c8e6505c-1b0a-44fc-a316-9a6434229614","amount_money": {"amount": 100,"currency": "USD"},"card_nonce": "cnon:CBASEB3xahyv00aJOseCdItaTHU"}'
Lost connection to device.

**Comment by StephenJosey** [comment] 2020-01-16 16:17
That's a bit strange. Could you try running the curl command in a stand-alone terminal window? It doesn't need to be within Flutter (it's just an HTTP request). If that doesn't work can you print out "flutter doctor -v" output?

**Comment by StephenJosey** [comment] 2020-01-16 23:47
Actually, probably related to: https://github.com/square/in-app-payments-flutter-plugin/issues/82

Can you please try using an older version of Flutter (before 1.12)?

**Comment by sgehrman** [comment] 2020-01-18 09:22
Same issue, I'm using the latest flutter.

**Comment by sgehrman** [comment] 2020-01-18 11:35
FATAL EXCEPTION: CardResultHandler
E/AndroidRuntime(17332): Process: re.distantfutu.therapist_training, PID: 17332
E/AndroidRuntime(17332): java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.runOnUiThread(java.lang.Runnable)' on a null object reference
E/AndroidRuntime(17332): 	at sqip.flutter.internal.CardEntryModule$2.handleEnteredCardInBackground(CardEntryModule.java:132)
E/AndroidRuntime(17332): 	at sqip.internal.CardEntryActivityController$onCardNonceSuccess$1.run(CardEntryActivityController.kt:141)
E/AndroidRuntime(17332): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(17332): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(17332): 	at java.lang.Thread.run(Thread.java:919)
I/FIAM.Headless(17332): Removing display event listener

**Comment by StephenJosey** [comment] 2020-01-21 17:23
Hi @sgehrman as mentioned in the other issue (https://github.com/square/in-app-payments-flutter-plugin/issues/82), the latest version of Flutter causes breaking changes to the API. Please make sure to use the latest In-App Payments SDK, but an older version of Flutter (1.9 I believe). Let me know if that doesn't help.

**Comment by StephenJosey** [comment] 2020-01-21 22:43
Closing as duplicate of https://github.com/square/in-app-payments-flutter-plugin/issues/82. Please let me know if you feel that it's not the same issue.

**Closed by StephenJosey** 2020-01-21 22:43 UTC
Labels: bug, duplicate

**Comment by ankitpanwar8979** [comment] 2021-04-05 18:13
> FATAL EXCEPTION: CardResultHandler
> E/AndroidRuntime(17332): Process: re.distantfutu.therapist_training, PID: 17332
> E/AndroidRuntime(17332): java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.runOnUiThread(java.lang.Runnable)' on a null object reference
> E/AndroidRuntime(17332): at sqip.flutter.internal.CardEntryModule$2.handleEnteredCardInBackground(CardEntryModule.java:132)
> E/AndroidRuntime(17332): at sqip.internal.CardEntryActivityController$onCardNonceSuccess$1.run(CardEntryActivityController.kt:141)
> E/AndroidRuntime(17332): at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> E/AndroidRuntime(17332): at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> E/AndroidRuntime(17332): at java.lang.Thread.run(Thread.java:919)
> I/FIAM.Headless(17332): Removing display event listener

Hey there , i am getting the same error, have you found any solution for this?
