### ISSUE TITLE
Android app crashes after pressing save button in card entry flow

### ISSUE THREAD

**Issue by shajedulislam** [square/in-app-payments-flutter-plugin#91] opened 2020-02-25 07:14 UTC
Flutter app crashes after saving card info in android only.

I am using the latest Flutter version and Square plugin.

### Log

```
E/AndroidRuntime(11211): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(11211): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/AndroidRuntime(11211): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.app.Activity.getResources()' on a null object reference
E/AndroidRuntime(11211): 	at sqip.flutter.internal.CardEntryModule.readCardEntryCloseExitAnimationDurationMs(CardEntryModule.java:215)
E/AndroidRuntime(11211): 	at sqip.flutter.internal.CardEntryModule.access$500(CardEntryModule.java:52)
E/AndroidRuntime(11211): 	at sqip.flutter.internal.CardEntryModule$1$1.onResult(CardEntryModule.java:86)
E/AndroidRuntime(11211): 	at sqip.flutter.internal.CardEntryModule$1$1.onResult(CardEntryModule.java:73)
E/AndroidRuntime(11211): 	at sqip.internal.CardEntryActivity$Companion.onActivityResult(CardEntryActivity.kt:596)
E/AndroidRuntime(11211): 	at sqip.CardEntry.handleActivityResult(CardEntry.kt:58)
E/AndroidRuntime(11211): 	at sqip.flutter.internal.CardEntryModule$1.onActivityResult(CardEntryModule.java:73)
E/AndroidRuntime(11211): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEnginePluginRegistry.java:634)
E/AndroidRuntime(11211): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onActivityResult(FlutterEnginePluginRegistry.java:367)
E/AndroidRuntime(11211): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:546)
E/AndroidRuntime(11211): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:594)
E/AndroidRuntime(11211): 	at android.app.Activity.dispatchActivityResult(Activity.java:7454)
E/AndroidRuntime(11211): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4353)
E/AndroidRuntime(11211): 	... 11 more
I/Process (11211): Sending signal. PID: 11211 SIG: 9
```

**Comment by StephenJosey** [comment] 2020-02-25 17:44
Thanks for reporting this. Are you able to replicate this in the [example](https://github.com/square/in-app-payments-flutter-plugin/tree/master/example) application? I haven't been able to replicate this thus far.

**Comment by shajedulislam** [comment] 2020-02-27 11:38
yes @StephenJosey . It works fine in IOS. Even I have tested payment with square sanbox but the problem is in Android just after pressing the save button in card entry flow. Not only me but other devs also facing this. Some people said they have solved by downgrading flutter into v1.9.1 + hotfix 6 which is not a good solution. Now I can not publish the app on store just because of this.

**Comment by StephenJosey** [comment] 2020-02-27 17:48
Ah, right, so in that case it sounds similar to: https://github.com/square/in-app-payments-flutter-plugin/issues/82 which unfortunately still hasn't been resolved. We currently do not support newer versions of Flutter with this plugin (sorry I missed that in my initial comment). We're working on it, though, hang tight!

**Comment by shajedulislam** [comment] 2020-03-03 07:11
hey @StephenJosey, Still no solution ? dying here with it !

**Comment by skypopcorn1** [comment] 2020-04-21 23:54
Hey @StephenJosey  - any update here? I have several other dependencies in my project that don't work with older versions of flutter (ie pre 1.12)

**Comment by wcyankees424** [comment] 2020-04-24 04:19
I too am looking to use this plugin is there any idea as to when this will be fixed?

**Comment by skypopcorn1** [comment] 2020-04-25 23:55
I have created an interim workaround solution. Currently only covers iOS, adding Android shortly.

https://github.com/skypopcorn1/squarepaymentsflutternativesdksample

**Comment by StephenJosey** [comment] 2020-06-02 17:13
Closing as duplicate of: https://github.com/square/in-app-payments-flutter-plugin/issues/82. We are still working on this but no ETA unfortunately.

**Closed by StephenJosey** 2020-06-02 17:13 UTC
Labels: bug, duplicate
