### ISSUE TITLE
Apple Pay view according to Apple Pay Interface Guidelines

### ISSUE THREAD

**Issue by AlexanderArendar** [square/in-app-payments-flutter-plugin#56] opened 2019-08-19 13:04 UTC
Apple provides guidelines on how the app integrating Apple Pay should look like.
It is described here: https://developer.apple.com/design/human-interface-guidelines/apple-pay/overview/introduction/

Our app was rejected by Apple with requirement that the "CONTACT" section should be included.
I can't find in the plugin documentation how can I pass contact info to the `InAppPayments.requestApplePayNonce` method.
I can only pass there "summaryLabel" and that's all. 

Could you advice how can I include "Contact" info and possible all other info blocks from the Apple guidelines?

**Comment by hukid** [comment] 2019-08-20 00:08
Closing this issue as @AlexanderArendar confirmed the app was rejected due to they provided wrong info in the summaryLabel.

Will reopen this issue if correcting summaryLabel doesn't solve the issue.

**Closed by hukid** 2019-08-20 00:08 UTC
