### ISSUE TITLE
error on build androidx

### ISSUE THREAD

**Issue by hipimy** [square/in-app-payments-flutter-plugin#36] opened 2019-03-05 07:32 UTC
C:\Users\acer\Documents\Git\flutter\.pub-cache\hosted\pub.dartlang.org\square_in_app_payments-1.1.0\android\src\main\java\sqip\flutter\internal\CardEntryModule.java:39: error: package org.jetbrains.annotations does not exist
import org.jetbrains.annotations.NotNull;
                                ^
C:\Users\acer\Documents\Git\flutter\.pub-cache\hosted\pub.dartlang.org\square_in_app_payments-1.1.0\android\src\main\java\sqip\flutter\internal\CardEntryModule.java:83: error: cannot find symbol
      @NotNull @Override
       ^
  symbol: class NotNull
2 errors
         *********************************************************
WARNING: This version of android_intent will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.
         *********************************************************
Finished with error: Gradle task assembleDebug failed with exit code 1

if i remove the square_in_app_payments: ^1.1.0, project can be build. what is the issues

**Comment by hukid** [comment] 2019-03-05 18:31
@hipimy Thanks for reporting this issue. It seems your project cannot load org.jetbrains.annotations as dependencies. I cannot repro this with the example project.

May I know what's the gradle version you are using? Did you just upgrade your project to AndroidX?

Can you try to add `compileonly 'com.intellij:annotations:+@jar'` in your gradle dependencies and see if that issue still there?

**Comment by hipimy** [comment] 2019-03-05 19:55
gradle wrapper distributionUrl=https\://services.gradle.org/distributions/gradle-5.1.1-all.zip

compileonly 'com.intellij:annotations:+@jar' this need to add to build.gradle project level or app-level?
 
So i decided  to use in app-level build.gradle :
`dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.1.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.1.2'
    implementation 'androidx.appcompat:appcompat:1.0.2'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    provided 'com.intellij:annotations:+@jar'
}`

this error still appear 
`C:\Users\acer\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\square_in_app_payments-1.1.0\android\src\main\java\sqip\flutter\internal\CardEntryModule.java:39: error: package org.jetbrains.annotations does not exist
import org.jetbrains.annotations.NotNull;
                                ^
C:\Users\acer\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\square_in_app_payments-1.1.0\android\src\main\java\sqip\flutter\internal\CardEntryModule.java:83: error: cannot find symbol
      @NotNull @Override
       ^
  symbol: class NotNull
2 errors
Finished with error: Gradle task assembleDebug failed with exit code 1`

My project already migrate to androidx.

**Comment by hukid** [comment] 2019-03-05 21:21
Hi, 

I think this link https://stackoverflow.com/questions/53702038/android-gradle-5-0-updatecause-org-jetbrains-plugins-gradle-tooling-util may help you understand the issue and the solution.

The problem is due to gradle 5.0 and above. If you use gradle 4.10, the problem should be gone.

If you have to stay with gradle 5.1.1, you have to manually add `compileOnly 'com.intellij:annotations:+@jar'` to square_in_app_payments module's build.gradle file.

**Comment by hukid** [comment] 2019-03-07 18:01
@hipimy would you please let us know if your issue have been resolved?

**Comment by hipimy** [comment] 2019-03-10 08:23
@hukid yup.I stay with gradle 5.1.1 then need to add compileOnly 'com.intellij:annotations:+@jar' to square_in_app_payments module's build.gradle file. Issues was resolve. I will find another solution without modified the packages. Thanks

**Comment by hukid** [comment] 2019-03-11 16:51
Great! Closing this issue now.

**Closed by hukid** 2019-03-11 16:51 UTC
