### ISSUE TITLE
Exception: sqip.internal.event.LogEventsResponse not present 

### ISSUE THREAD

**Issue by d3vtoolsmith** [square/in-app-payments-flutter-plugin#72] opened 2019-10-31 04:50 UTC
We started getting a hard crash/exception only on Android phones only when the user is trying add a new card and either backs out (by clicking the back arrow) or successfully adds a card and we call InAppPayments.completeCardEntry(...) to complete the entry and dismiss sqip screen (it crashes as sqip card screen is being dismissed).

This issue doesn't happen on iOS - only Android. This issue also doesn't happen when running in debug mode. It seems to occur 100% of the time when running a released build on a device.
This issue got introduced with one of the recent upgrades of the various libraries we're using, though doesn't seem like going from sqip 1.2.2 to 1.2.3 is the root cause (tried both sqip versions as well as Flutter up to 1.9.1 hotfix 6).

Hopefully the following exception will be sufficient to track this, though let me know if you need any more info. Thank you!

**EXCEPTION**

```
Fatal Exception: java.lang.TypeNotPresentException: 
Type sqip.internal.event.LogEventsResponse not present
       at libcore.reflect.ParameterizedTypeImpl.getRawType(ParameterizedTypeImpl.java:67)
       at libcore.reflect.ParameterizedTypeImpl.getResolvedType(ParameterizedTypeImpl.java:76)
       at libcore.reflect.ListOfTypes.resolveTypes(ListOfTypes.java:70)
       at libcore.reflect.ListOfTypes.getResolvedTypes(ListOfTypes.java:55)
       at libcore.reflect.ParameterizedTypeImpl.getResolvedType(ParameterizedTypeImpl.java:75)
       at libcore.reflect.Types.getType(Types.java:56)
       at java.lang.reflect.Method.getGenericReturnType(Method.java:177)
       at j.M.a(:2)
       at j.L.a(:8)
       at j.K.invoke(:5)
       at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
       at $Proxy3.a()
       at sqip.internal.b.c$a.a(:59)
       at sqip.internal.b.c$a.a(:1)
       at sqip.internal.b.d.run(:1)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
```

**ENVIRONMENT**

[✓] Flutter (Channel unknown, v1.7.10, on Mac OS X 10.14.6 18G95, locale en-US) 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.39.2)

square_in_app_payments: ^1.2.3

**Comment by hukid** [comment] 2019-11-13 00:30
@d3vtoolsmith Can you please share us your dependencies list? the `pubspec.yaml` maybe useful.

**Comment by d3vtoolsmith** [comment] 2019-11-13 16:49
Definitely, here you go:
(we did upgrade most of the dependencies to the latest versions when (after which?) this square issue surfaced)

```
  cupertino_icons: ^0.1.2
  flutter_launcher_icons: "^0.7.3"
  flutter_statusbarcolor: ^0.2.2
  shared_preferences: ^0.5.3+4
  package_info: ^0.4.0+6
  sprintf: "^4.0.2"
  date_format: ^1.0.6
  uuid: ^2.0.2
  provider: ^3.0.1
  fluttertoast: ^3.1.3
  badges: ^1.1.0
  page_transition: ^1.1.3
  url_launcher: ^5.1.6
  firebase_core: ^0.4.0+9 #^0.3.4
  firebase_analytics: ^5.0.2 #^2.1.1+3
  firebase_crashlytics: ^0.1.0+3
  firebase_performance: ^0.3.0+5
  firebase_messaging: 5.1.4
  firebase_dynamic_links: ^0.5.0+1
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+5
  cloud_functions: ^0.4.1+1
  auto_size_text: ^2.1.0
  flutter_masked_text: ^0.8.0
  flutter_svg: ^0.14.2
  flutter_swiper : ^1.1.5
  flutter_page_indicator: ^0.0.3
  sliding_up_panel: ^0.3.6
  cached_network_image: ^1.1.1
  intl: ^0.16.0
  email_validator: ^1.0.0
  device_info: ^0.4.1+1
  fast_qr_reader_view: #^0.1.5
    git:
      url: git://github.com/facundomedica/fast_qr_reader_view.git  
  square_in_app_payments: ^1.2.3
  recase: ^2.0.1
```

**Comment by d3vtoolsmith** [comment] 2019-12-13 18:09
Do you have any updates on fixing this? It's a real problem affecting all our Android installations (hard uncatchable crash when trying to add a card).
Does v1.3.0 fix it? 
(I'm asking instead of trying because it's a nightmare to update to v1.3.0 because it results in underlying dependency conflicts between your SDK and our other dependencies - your SDK's dependency tree is insane, just for basic payment taking API calls. We're seriously considering moving off of Square if this is not solved before the end of the year.)

**Comment by okenshields** [comment] 2019-12-17 19:16
> Do you have any updates on fixing this? It's a real problem affecting all our Android installations (hard uncatchable crash when trying to add a card).
> Does v1.3.0 fix it?
> (I'm asking instead of trying because it's a nightmare to update to v1.3.0 because it results in underlying dependency conflicts between your SDK and our other dependencies - your SDK's dependency tree is insane, just for basic payment taking API calls. We're seriously considering moving off of Square if this is not solved before the end of the year.)

Hi, we were working on this internally and had an update: a new version for Android (1.3.1) will be released later today to fix this issue. Thanks for your patience.

**Comment by okenshields** [comment] 2019-12-17 22:29
Android IAP SDK 1.3.1 is now released https://developer.squareupstaging.com/docs/changelog/mobile-logs/2019-12-17 .
Please follow https://github.com/square/in-app-payments-flutter-plugin/blob/master/doc/versioning.md to specify the new version for Android.

Could you please help a little more details regarding the "`underlying dependency conflicts between your SDK and our other dependencies`" you mentioned? We were wondering if it's referring to the same card entry exception or something else. Thanks!

**Comment by d3vtoolsmith** [comment] 2019-12-22 03:53
Thank you for working on this.
We're trying to switch to the latest version of the plugin/SDK, but as I briefly mentioned last time, we are now running into build errors because of conflicting dependencies (Android build only, iOS compiles and works fine). This is the exact error we're getting:

```
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Could not determine the dependencies of task ':square_in_app_payments:compileReleaseAidl'.
> In project 'app' a resolved Google Play services library dependency depends on another at an exact version (e.g. "[1.3.1
  ,2.3]", but isn't being resolved to that version. Behavior exhibited by the library will be unknown.
                                                                        
  Dependency failing: com.nds.threeds:threedssdk-release:1.1.17 -> net.minidev:json-smart@[1.3.1,2.3], but json-smart vers
  ion was 2.3.                                                          
                                                                        
  The following dependencies are project dependencies that are direct or have transitive dependencies that lead to the art
  ifact with the issue.                                                 
  -- Project 'app' depends on project 'square_in_app_payments' which depends onto com.squareup.sdk.in-app-payments:buyer-v
  erification@1.3.0                                                     
  -- Project 'app' depends on project 'square_in_app_payments' which depends onto com.nds.threeds:core@1.1.5
  -- Project 'app' depends on project 'square_in_app_payments' which depends onto com.nds.threeds:widget@1.1.5
  -- Project 'app' depends on project 'square_in_app_payments' which depends onto com.nds.threeds:threedssdk-release@1.1.1
  7                                                                     
  -- Project 'app' depends on project 'square_in_app_payments' which depends onto net.minidev:json-smart@2.3
```

This is the exact listing of current app dependencies (which build fine on both platforms when using `square_in_app_payments` v1.2.3:

```
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_launcher_icons: "^0.7.3"
  flutter_statusbarcolor: ^0.2.2
  shared_preferences: ^0.5.3+4
  package_info: ^0.4.0+6
  sprintf: "^4.0.2"
  date_format: ^1.0.6
  uuid: ^2.0.2
  provider: ^3.0.1
  bot_toast: ^2.2.0
  badges: ^1.1.0
  page_transition: ^1.1.3
  url_launcher: ^5.1.6
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  firebase_crashlytics: ^0.1.0+3
  firebase_performance: ^0.3.0+5
  firebase_messaging: 5.1.4
  firebase_dynamic_links: ^0.5.0+1
  firebase_remote_config: ^0.3.0
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+5
  cloud_functions: ^0.4.1+1
  auto_size_text: ^2.1.0
  flutter_masked_text: ^0.8.0
  flutter_svg: ^0.14.2
  flutter_swiper : ^1.1.5
  flutter_page_indicator: ^0.0.3
  sliding_up_panel: ^0.3.6
  cached_network_image: ^1.1.1
  intl: ^0.16.0
  email_validator: ^1.0.0
  device_info: ^0.4.1+1
  flutter_google_places: ^0.2.3
  google_maps_webservice: ^0.0.16
  flutter_offline: ^0.3.0
  app_review: ^1.0.0
  open_appstore: ^1.0.2
  in_app_update: ^1.1.6
  fast_qr_reader_view: #^0.1.5
    git:
      url: git://github.com/facundomedica/fast_qr_reader_view.git  
  square_in_app_payments: ^1.3.0
  recase: ^2.0.1
```

**Comment by fka3** [comment] 2020-01-31 06:28
The root issue here is proguard (which is not compatible with IAP 1.2.3) wrongly believing that the class was unused and stripping it out from the APK.  If upgrading to IAP 1.3.1 (which fixes the issue), it should also be possible to resolve the issue _without_ upgrading by adding an exception to the proguard rules file, something like `-keep class squip.**`

That should get you un-stuck while staying at IAP 1.2.3.

Obviously, we'd _like_ for you to upgrade to the most current version, but that choice is up to you.  I'm a little puzzled that the dependency analyzer isn't resolving json-smart in the text you have above; I see a pin at version 2.3 by us, and a pin to the _inclusive_ range [ 1.3.1, 2.3 ]... and it seems both constraints can be me at version 2.3, so I'm puzzled why it's not resolving.  That said, you're also citing square_in_app_payments 1.3.0, which doens't _quite_ solve your issue anyway, so _that_ needs to move up to 1.3.1.

**Comment by d3vtoolsmith** [comment] 2020-02-05 23:08
We've gone through upgrading all the dependencies to be able to reference 1.3.0, which compiled fine after everything was upgraded. 

There is no 1.3.1 version of the Flutter plug-in, so we assumed that you meant 1.3.1 of the SDK, which we explicitly referenced inside `build.gradle` and recompiled with `flutter clean + flutter build appbundle` (as per https://github.com/square/in-app-payments-flutter-plugin/blob/master/doc/versioning.md).

Sadly, we're still experiencing the same hard crash when trying to add a card, when that card ui is being closed. (As before, this is an Android-only issue, and **only when running on a device after releasing through the Play Store**.)

**Comment by py-zoid** [comment] 2020-03-07 23:24
> We've gone through upgrading all the dependencies to be able to reference 1.3.0, which compiled fine after everything was upgraded.
> 
> There is no 1.3.1 version of the Flutter plug-in, so we assumed that you meant 1.3.1 of the SDK, which we explicitly referenced inside `build.gradle` and recompiled with `flutter clean + flutter build appbundle` (as per https://github.com/square/in-app-payments-flutter-plugin/blob/master/doc/versioning.md).
> 
> Sadly, we're still experiencing the same hard crash when trying to add a card, when that card ui is being closed. (As before, this is an Android-only issue, and **only when running on a device after releasing through the Play Store**.)

Did you find a fix? I'm experiencing the same issue!

**Comment by d3vtoolsmith** [comment] 2020-03-08 01:41
> 
> Did you find a fix? I'm experiencing the same issue!

No, sadly all the claimed fixes do not solve the issue. Obviously noone actually did a simple test with my dependency list before claiming it's been fixed.

It's sad, but we are working on switching to Stripe.

**Comment by py-zoid** [comment] 2020-03-08 16:55
> > Did you find a fix? I'm experiencing the same issue!
> 
> No, sadly all the claimed fixes do not solve the issue. Obviously noone actually did a simple test with my dependency list before claiming it's been fixed.
> 
> It's sad, but we are working on switching to Stripe.

I think I know what the issue is. As @fka3 suggested it's the issue with the proguard rules. From your app/build.gradle file, comment out the shrinkResources, minifyEnabled, useProguard and proguardFiles lines under release buildType. This solved the issue for me. It doesn't crash while returning to the app after adding card in release mode anymore.

**Comment by d3vtoolsmith** [comment] 2020-03-23 21:32
Removing all those (shrinkResources, minifyEnabled, useProguard and proguardFiles) does solve that, but obviously it's also removing all the optimizations.

**Comment by StephenJosey** [comment] 2020-06-02 16:38
Hey folks, just following up here - is this issue resolved, now? It sounds like you all found out how to work around it but just making sure there's nothing I missed?

**Comment by d3vtoolsmith** [comment] 2020-06-02 17:04
The workaround does not work. Plugin still hard-crashes the app when Add Card is activated on an Android device.
Switching to Stripe.

**Comment by py-zoid** [comment] 2020-06-02 17:42
The workaround, as suggested by @d3vtoolsmith, is removing all the optimizations. Doing that increases my app size by more than 36%. I would definitely want you guys to fix this and release an update.

**Comment by StephenJosey** [comment] 2020-06-02 21:09
Thanks for confirming, and sorry to hear that. I've informed our team that this is still an issue so they can resolve it.

**Closed** 2020-07-02 08:11 UTC
Labels: bug
